enum eKOTH
{
	LOG_CRITICAL = 1,
	LOG_BASIC,
	LOG_VERBOSE,
	
	RPC_KOTH_CONFIG_SYNC = 239400,
	RPC_KOTH_EVENT_SYNC,
	RPC_KOTH_PROGRESS_SYNC,
	RPC_KOTH_PLAY_ALARM_SOUND,     
	RPC_KOTH_PLAY_VEHICLE_SOUND     
}